### ISSUE TITLE
Add way to fold part of trees

### ISSUE THREAD

**Issue by PeeHaa** [DaveRandom/json-prettifier#1]
Would be nice to have a way to fold part of the tree.

**Comment by DaveRandom** [comment]
I've kicked this idea around before, crucially this feature would need to retain the property that selecting text around a folded block and copying it to the clipboard would copy the entire formatted block of text. a simple `display:none`/`visibility:hidden` approach would break this (I think?)

Open to suggestions.

**Comment by PeeHaa** [comment]
I see. Need to do some investigating. Maybe faking it with `height: 0`  will work.

Will dick around a bit and report back.
